version: 2.1

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
jobs:
  build:
    docker:
      - image: hubci/gotham:0.10
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: "Build Website With Gotham"
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              HUGO_ENV=production gotham -v -s src/
            else
              HUGO_ENV=staging gotham -v -s src/ --config config.yml,staging-config.yml
            fi
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public
  deploy:
    docker:
      - image: hubci/gotham:0.10
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run:
          name: "Deploy website"
          command: |
            echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts

            if [[ $CIRCLE_BRANCH == "master" ]]; then
              rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/gothamhq/www/public_html
            else
              rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/gothamhq/staging-www/public_html
            fi
